# Generated by Django 5.1 on 2024-08-28 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texnomart', '0002_alter_category_options_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
